# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tvShow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for tvShow
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Alamofire', '~> 5.4'
  pod 'Swinject'
  pod 'SwinjectAutoregistration'
  pod 'SwinjectStoryboard'
  pod 'Kingfisher', '~> 6.0'

  target 'tvShowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tvShowUITests' do
    # Pods for testing
  end

end
